# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 905f012b29c26deb25aafce1f0a8da9e0a0dcdaca6ffaa69ec6c09c711c2811f5330c0f529463fa8221c2ecb187841980b131a2db677ebe7b2e9200cd9cfb0c8

test:
  secret_key_base: 7c4bc5e1a150ee856a68fd1bde3442008608d09e1f81946c34f3ae5df2263863c6d855c5d1337f50d33f5ceac71092b9e6720ba60dcc6791ff6c9dabbfdd3f42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
